//
//  main.swift
//  Monext
//
//  Created by lucas bianciotto  on 26/02/2026.
//

import Foundation

// MARK: - Helpers

func readEnvFile(at path: String) -> [String: String] {
    guard let content = try? String(contentsOfFile: path, encoding: .utf8) else {
        return [:]
    }

    var result: [String: String] = [:]
    for line in content.components(separatedBy: .newlines) {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        // Ignorer les commentaires et les lignes vides
        guard !trimmed.isEmpty, !trimmed.hasPrefix("#") else { continue }
        let parts = trimmed.components(separatedBy: "=")
        guard parts.count >= 2 else { continue }
        let key = parts[0].trimmingCharacters(in: .whitespaces)
        let value = parts.dropFirst().joined(separator: "=").trimmingCharacters(in: .whitespaces)
        result[key] = value
    }
    return result
}

func resolveKey(named name: String) -> String {
    // 1. Variables d'environnement (CI / GitHub Actions)
    if let value = ProcessInfo.processInfo.environment[name], !value.isEmpty {
        fputs("✅ \(name) found in environment variables\n", stderr)
        return value
    }

    // 2. Fichier .env.local (développement local)
    let workDir = FileManager.default.currentDirectoryPath
    let envLocalPath = URL(fileURLWithPath: workDir).appendingPathComponent(".env.local").path
    let envVars = readEnvFile(at: envLocalPath)

    if let value = envVars[name], !value.isEmpty {
        fputs("✅ \(name) found in .env.local\n", stderr)
        return value
    }

    // 3. Clé vide avec warning
    fputs("⚠️  Warning: \(name) not found. Set it in .env.local or as environment variable.\n", stderr)
    fputs("   → Copy .env.local.example to .env.local and fill in your values.\n", stderr)
    return ""
}

func toByteArray(_ string: String) -> String {
    return string.utf8
        .map { String(format: "0x%02x", $0) }
        .joined(separator: ", ")
}

// MARK: - Main

guard CommandLine.arguments.count > 1 else {
    fputs("❌ Usage: InjectSecretsExecutable <output_path>\n", stderr)
    exit(1)
}

let outputPath = CommandLine.arguments[1]

let netecteraAPIKey = resolveKey(named: "NETCETERA_API_KEY")
let netecteraBytes = toByteArray(netecteraAPIKey)

let content = """
// ⚠️ Auto-generated by InjectSecretsPlugin - do not edit manually
// This file is gitignored and regenerated at each build

internal enum APIConfig {

    /// Netcetera 3DS SDK API Key
    /// Stored as bytes to avoid plain text exposure in the binary
    static var netecteraAPIKey: String {
        let bytes: [UInt8] = [\(netecteraBytes)]
        return String(bytes: bytes, encoding: .utf8) ?? ""
    }

}
"""

do {
    try content.write(toFile: outputPath, atomically: true, encoding: .utf8)
    fputs("✅ APIConfig.swift generated at \(outputPath)\n", stderr)
} catch {
    fputs("❌ Failed to write APIConfig.swift: \(error)\n", stderr)
    exit(1)
}
