default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :testflight do
    build_app(
      scheme: "Example"
    )
    upload_to_testflight(
        api_key: app_store_connect_api_key(
            key_id: ENV['APPSTORE_KEY_ID'],
            issuer_id: ENV['APPSTORE_ISSUER_ID'],
            key_content: ENV['APPSTORE_KEY_CONTENT']
        )
    )
  end
end
